apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-be
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-be
  template:
    metadata:
      labels:
        app: chatbot-be
    spec:
      containers:
      - name: chatbot-be
        image: kwonjh0406/chatbot-be:IMAGE_TAG
        ports:
        - containerPort: 8080